### PR TITLE
Use icinga color for timerange menu

### PR DESCRIPTION
**Pull request by epinter**

### CODE REVIEW

**Comment by Mikesch-mp** [comment]
Hello Emerson,

the color i use is the Icinga blue. And i want the color change on mouseover! 

Best regards,

**Comment by epinter** [comment]
When you try to use another theme that use another color that is not blue, you will need this change...

**Comment by dnsmichi** [comment]
I'm not a CSS guru, but @icinga-blue would reference the framework's css which is then resolved by the less compiler, or so. I think @epinter 's patch is more correct than hardcoding a color code in a module's css, but I need to test the patch when I get time :)

**Comment by Mikesch-mp** [comment]
I tested it and @epinter is right with the @icinga-color. With this it will change to whatever the color is in the actual theme.

@Epinter please edit your change for to this code and then i will add the pull request.
```
.grafana-menu-navigation:hover a.main {
  color: @body-bg-color;
  background: @icinga-blue;
}
```

**Comment by Mikesch-mp** [comment]
Ahh and for future prull request, give please a litle description what the change shold do. iam only a stupid developer and it takes a lot of time to understand the pull requests.

**Comment by epinter** [comment]
Do you mind if I use ? I think is makes more sense and the result is the same (background blue and white text).

.grafana-menu-navigation:hover a.main {
  color: @text-color-inverted;
  background-color: @icinga-blue;
}

**Comment by Mikesch-mp** [comment]
Thats even better :)

**Pull request merged**
