### PR TITLE
Fix CSS menu on webkit browsers

### PR DESCRIPTION
**Pull request by epinter**
Tested on Vivaldi and Chrome

### CODE REVIEW

**Comment by Mikesch-mp** [comment]
Hi Emerson,

first the menu should not be visible when user scrolls down and it is "behind" the quick action bar (z.-index).
And the position change does'nt really change anything in my 4 Browsers (Chrome,Firefox,IE and Edge)

What behavior you wantto change with this 2 lines?

Regards,
Carsten

**Comment by epinter** [comment]
I don't want to change any behaviour, I want to solve the bug that occurs when I try to use the menu on Chrome. When I move the mouse down, the menu disappears before any click.

**Comment by Mikesch-mp** [comment]
Emerson this is what happens on Chrome with your fix:

image

**Comment by epinter** [comment]
Weird. This is not happening to me. I tested again now, cleaned cache, on Vivaldi, Chrome and Firefox  using private browsing. This is not happening to me.

The way the menu appears on your screenshot, looks like there's a position:absolute somewhere...

Before this change, the menu didn't work, completely useless...

**Comment by Mikesch-mp** [comment]
This is what the Developertools see:
image
image
image

When iam correct it comes from z-index

**Comment by epinter** [comment]
Looking again on your screenshot I got the problem ... I overlooked the menu while scrolling the page. I will try to set a negative z-index on img

**Comment by epinter** [comment]
Actually, z-index is not needed. I will create another pull request.

**Pull request closed without merging**
