### PR TITLE
display Graphs as iframe instead of rendered image in direct mode

### PR DESCRIPTION
**Pull request by neubi4**
Changing the graphs in direct mode to iframes. This brings multiple advantages:

- single datapoints are visible with mouse hovering over graph
- better usability feeling on page loads
- we can use the full width of the page
- zooming in is possible without page reload (sadly there is no way to zoom out again :disappointed:)

additional fixes:

- fixed not working variable $displayLink
- displays an text link to grafana in direct mode
- reformated Grapher.php, replaced tabs with spaces so this file uses consistent indents
- fixed typo in readme.md

### CODE REVIEW

**Comment by dnsmichi** [comment]
I'd opt for tabs instead of spaces, and do that change in a separate commit. Right now it is really hard to figure out what exactly you've changed for adding the feature. Can you split that up for better review please? :)

**Comment by neubi4** [comment]
I have splitted the reformat to a seperate commit and switched spaces to tabs ;)

**Comment by dnsmichi** [comment]
Ah cool, thanks :)

**Comment by Mikesch-mp** [comment]
Hello Martin,

thanks for your PR. Can i cherrypick the iframe code ? i would like to set it as a third option, so the users can choose how to display the graphs.

Regards,

Carsten


P.S.: iam just under heavy workload, so things take a bit more time these days

**Comment by Mikesch-mp** [comment]
I added iframes option with some code from your PR. See 3efcff49e3310570aa4a45cce2f4ef29cab47035

**Pull request closed without merging**
