### PR TITLE
Disable autorefresh for grafana iframe

### PR DESCRIPTION
**Pull request by friesoft**
This disables autorefresh for the iframe. All work was done by @thox

In reference to this issue: https://github.com/Icinga/icingaweb2/issues/2820

### CODE REVIEW

**Comment by friesoft** [comment]
ping :)

**Comment by Mikesch-mp** [comment]
Pong 🙂,

Thank fir the commit. I plan a release soon. Just under heavy load at the moment.

**Comment by aledr** [comment]
It seems not correct for me...
Look what I have after 5 seconds on Hosts or Services Page.

image

**Comment by Mikesch-mp** [comment]
Please reload the page once with "shift + f5" or clear your complete browser cache. i had that too until i did the hard refresh.

**Comment by aledr** [comment]
Any news about the fix?
Would it be better to open an _Issue_?

**Comment by Mikesch-mp** [comment]
Currently iam thinking about to remove that code again. I cant maintain it and the authors doesnt reply :(

**Comment by SgtSiff** [comment]
Any word on this?

Cheers

**Comment by nilmerg** [comment]
I've provided a fix for this, I think, please try this if possible: #263

**Pull request merged**
