### PR TITLE
Added check_command variable (&var-command=...) to graph-urls. 

### PR DESCRIPTION
**Pull request by matthiaswe**
Gives you much better filter posibilities when creating grafana dashboards.
Without check_command variable handed to grafana, it's sometimes not possible to select to needed influxdb table. In addition to that, you save a query in grafana to dynamically query the correct table as panel template and speeds up graphs. Since you do not need to use the "var-command" variable, the pull request adds more fexibility without any other restriction.

### CODE REVIEW

**Comment by Mikesch-mp** [comment]
Hi,

i dont really see the need for this. If i have a service with ping4 command for example and a dashbaord with  one graph "hard coded" to ping4 measurement. It will be much faster then with another variable to handle. The only thing i see this would speed up a litle is in the default dashboard, but the exrta query is even on  on my raspery pi 2 very fast.
Normaly i dont need post the service name to grafana, its only to put the name of it, if wanted, as graph title. 
To get the command just use Grafana templating with 

`SHOW MEASUREMENTS where  hostname =~ /^$hostname$/ and service =~ /^$service$/ LIMIT 1;`

**Comment by matthiaswe** [comment]
Hi,

i agree to you in a regular situation. We use Icingaweb2 with your module in a very big environment. While scaling the number of hosts to a very big number, you have to change existing services to new needs. In our case we had to switch the check_command for an existing service-check without changing service-name. This leads us to the problem, that your query above hits the wrong (old check_command) table and doesn't display a correct graph. Right now, we do not want to throw the old data in our influxDB away, so adding the &var-command adds the posibility to hit the correct table. Do you see any potential impact on existing features?

We'd be very happy to integrate the variable, so we can use your original master-branch. If you've another idea how we could use the configuration (custom-var) with check_command, we're open for other solutions. The suggestion in a closed issue writing vars.checkCommand = check_command sadly doesn't work for us either, since we use icingaweb2-director for service-configuration and with this, it's not possible to write check_command to custom-vars.

Regards,
Matthias

**Comment by Mikesch-mp** [comment]
Hi Matthias,

if you still want to have the old data, i would rename the old measurement. In the [InfluxDB](http://docs.influxdata.com/influxdb/v1.4/query_language/data_exploration/#the-into-clause) docs is a workaround for renaming, maybe this can solve your problem.

```
SELECT * INTO new_name FROM old_name
DROP MEASUREMENT old_name
```

Regards,
Carsten

**Comment by matthiaswe** [comment]
Hi Carsten,

thanks for your quick responses!

Renaming the table is in our case a problem, too. Example is:

At the beginning Icinga2 was configured as follows:
- Linux- + Windowsservers have services named "disk" with check_command "disk"

Now Icinga2 had to be changed to:
- Linuxservers have services named "disk" with check_command "disk"
- Linuxservers have services named "disk" with check_command "disk-windows"

If i rename the disk measurement i'd loose linux historic data. If not, windows-servers don't hit disk-windows measurement. Building a second dashboard with "disk-windows" as graph filter doesn't hit either, sind "disk" matches both cases.

Regards,
Matthias

**Comment by Mikesch-mp** [comment]
Hi Matthias,

you can still add a where clause to the select :) The other thing is , you can also have 2 measurements in one select of Grafana. just use something like that in you graph 

`select /disk|disk-windows/ .....` 

i did that too, to have only one graph for both worlds.
I will do some tests and then decide, because i think it will break existings installations. Grafana is a bitch if you send more vars then the dashboards knows :(

Regards,
Carsten

**Comment by matthiaswe** [comment]
Hi Carsten,

okay, i didn't get grafana this way until now;) Thanks for testing the usecase. Meanwhile i'll try your approach with two measurements in one select. That might help. I'll let you know if this works!

Regards,
Matthias

**Comment by Mikesch-mp** [comment]
HI @matthiaswe,

i tested it and it does not break anything. But i did the code a bit different.
I added you to the module.info, because this was your idea :) 

Best regards,
Carsten

**Pull request closed without merging**
